// Copyright 2024 Tokamak contributors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// GENERATED — do not edit by hand.
// Regenerate via: Scripts/gen-localizations.sh
// Source: Sources/TokamakDemo/Resources/Localizable.xcstrings

/// Generated English/Ukrainian demo string tables parsed from Localizable.xcstrings.
/// Keys are the English source strings (same convention as the hand-maintained tables).
/// Consumed by `registerDemoLocalizations()` to populate `LocalizationCatalog.shared`.
enum _GeneratedDemoLocalizations {
  static let en: [String: String] = [
    "(disabled under strict concurrency — see TaskDemo.swift)": "(disabled under strict concurrency — see TaskDemo.swift)",
    ".animation": ".animation",
    ".modifier": ".modifier",
    ".move(edge: .leading)": ".move(edge: .leading)",
    ".offset(x: 100, y: 100)": ".offset(x: 100, y: 100)",
    ".opacity": ".opacity",
    ".opacity + .slide": ".opacity + .slide",
    ".opacity/.scale": ".opacity/.scale",
    ".resizable() filling a 96×48 frame": ".resizable() filling a 96×48 frame",
    ".scale": ".scale",
    ".scaledToFill() (object-fit)": ".scaledToFill() (object-fit)",
    ".scaledToFit() (object-fit: contain)": ".scaledToFit() (object-fit: contain)",
    ".slide": ".slide",
    "0": "0",
    "1": "1",
    "1-10": "1-10",
    "1. Set the color to yellow": "1. Set the color to yellow",
    "11-20": "11-20",
    "1st tap gesture": "1st tap gesture",
    "2. Transform if the color is yellow -> green": "2. Transform if the color is yellow -> green",
    "3. Transform if the color is green -> blue": "3. Transform if the color is green -> blue",
    "4. Use the final color in an overlay.": "4. Use the final color in an overlay.",
    "<font color='red'>Sanitized Text in Unsanitized VStack</font>": "<font color='red'>Sanitized Text in Unsanitized VStack</font>",
    "<font color='red'>Sanitized Text</font>": "<font color='red'>Sanitized Text</font>",
    "<font color='red'>Segmented ": "<font color='red'>Segmented ",
    "<font color='red'>Text in Unsanitized VStack</font>": "<font color='red'>Text in Unsanitized VStack</font>",
    "<font color='red'>Unsanitized Text</font>": "<font color='red'>Unsanitized Text</font>",
    "Account": "Account",
    "Actions": "Actions",
    "Adaptive LazyVGrid": "Adaptive LazyVGrid",
    "Add item": "Add item",
    "An unlabeled group box groups related controls together.": "An unlabeled group box groups related controls together.",
    "Appointment date:": "Appointment date:",
    "Appointment time:": "Appointment time:",
    "Async `.task` fetch demo": "Async `.task` fetch demo",
    "Blue Style": "Blue Style",
    "Bookmark": "Bookmark",
    "Bottom": "Bottom",
    "Bottom Pane": "Bottom Pane",
    "Brightness: 80%": "Brightness: 80%",
    "Button": "Button",
    "Circular gauge style": "Circular gauge style",
    "Commits: 0": "Commits: 0",
    "Committed: —": "Committed: —",
    "Complex": "Complex",
    "Confirm:": "Confirm:",
    "Console content": "Console content",
    "Content of Tab One": "Content of Tab One",
    "Content of Tab Two": "Content of Tab Two",
    "Custom Font": "Custom Font",
    "Decorative (empty alt)": "Decorative (empty alt)",
    "Default": "Default",
    "Default color: red (this won't show on the innermost because it never 'changed').": "Default color: red (this won't show on the innermost because it never 'changed').",
    "Default label (title + icon)": "Default label (title + icon)",
    "Delay": "Delay",
    "Delete / reorder affordances appear while editMode.isEditing.": "Delete / reorder affordances appear while editMode.isEditing.",
    "Detail content": "Detail content",
    "Determinate": "Determinate",
    "Display": "Display",
    "Drag Gestures": "Drag Gestures",
    "DynamicViewContent": "DynamicViewContent",
    "EditButton": "EditButton",
    "Editor content": "Editor content",
    "End of section": "End of section",
    "Ethernet: Off": "Ethernet: Off",
    "Fallback Font": "Fallback Font",
    "Favorite": "Favorite",
    "Fill, with a custom label": "Fill, with a custom label",
    "First slider has steps at 0.3, 0.6, 0.9; second one has stops every 1/3 of the way": "First slider has steps at 0.3, 0.6, 0.9; second one has stops every 1/3 of the way",
    "Forced to bottom.": "Forced to bottom.",
    "Green Style": "Green Style",
    "Grouped Transition": "Grouped Transition",
    "HSplitView": "HSplitView",
    "Hello, world!": "Hello, world!",
    "Horizontal Spacing": "Horizontal Spacing",
    "I'm all fancy": "I'm all fancy",
    "I'm forced to the top": "I'm forced to the top",
    "I'm on bottom": "I'm on bottom",
    "I'm on top": "I'm on top",
    "Icon-only style": "Icon-only style",
    "Increased Total": "Increased Total",
    "Indeterminate": "Indeterminate",
    "Innermost child sets the color to blue.": "Innermost child sets the color to blue.",
    "I’m always checked!": "I’m always checked!",
    "Label": "Label",
    "Language": "Language",
    "Last action: None": "Last action: None",
    "LazyHStack": "LazyHStack",
    "LazyVStack": "LazyVStack",
    "Left": "Left",
    "Left Pane": "Left Pane",
    "Left side.": "Left side.",
    "Lightning": "Lightning",
    "Limit exceeded": "Limit exceeded",
    "Linear gauge style": "Linear gauge style",
    "Load": "Load",
    "Localization": "Localization",
    "LongPress Gestures": "LongPress Gestures",
    "Named (data-URI) source": "Named (data-URI) source",
    "Not tapped": "Not tapped",
    "One level up sets the color to green, and so on.": "One level up sets the color to green, and so on.",
    "Paste": "Paste",
    "PasteButton": "PasteButton",
    "Pasted: None": "Pasted: None",
    "Pick a text style...": "Pick a text style...",
    "Preferences are like reverse-environment values.": "Preferences are like reverse-environment values.",
    "Preferences can also be accessed and used immediately via a background or overlay:": "Preferences can also be accessed and used immediately via a background or overlay:",
    "Pressed": "Pressed",
    "Primary": "Primary",
    "Progress": "Progress",
    "Quaternary": "Quaternary",
    "Reads plain-text strings from the clipboard via payloadAction.": "Reads plain-text strings from the clipboard via payloadAction.",
    "Red Style": "Red Style",
    "Regular": "Regular",
    "Repeated Animation": "Repeated Animation",
    "Right": "Right",
    "Right Pane": "Right Pane",
    "Right side.": "Right side.",
    "Root": "Root",
    "Secondary": "Secondary",
    "Selection: 0": "Selection: 0",
    "Sidebar content": "Sidebar content",
    "Sign in with Apple": "Sign in with Apple",
    "SignInWithAppleButton": "SignInWithAppleButton",
    "Simple LazyHGrid": "Simple LazyHGrid",
    "Simple value gauge": "Simple value gauge",
    "Some nav-text": "Some nav-text",
    "Speed": "Speed",
    "Star": "Star",
    "Status: Live": "Status: Live",
    "Style": "Style",
    "Styles": "Styles",
    "Switch the app language. On the web the page reloads with the new language.": "Switch the app language. On the web the page reloads with the new language.",
    "System symbol (web placeholder — no SF Symbol pipeline)": "System symbol (web placeholder — no SF Symbol pipeline)",
    "THICK TEXT": "THICK TEXT",
    "Tab One": "Tab One",
    "Tab Two": "Tab Two",
    "Tap Gestures": "Tap Gestures",
    "Tap to toggle edit mode.": "Tap to toggle edit mode.",
    "Tertiary": "Tertiary",
    "Text style": "Text style",
    "Text: “”": "Text: “”",
    "Text</font>": "Text</font>",
    "Thick": "Thick",
    "Thin": "Thin",
    "This is super important": "This is super important",
    "This is the inital text": "This is the inital text",
    "This text has been concatenated": "This text has been concatenated",
    "This was super important": "This was super important",
    "Title and icon style": "Title and icon style",
    "Title-only style": "Title-only style",
    "Tokamak Demo": "Tokamak Demo",
    "Top": "Top",
    "Top Pane": "Top Pane",
    "True Tone: On": "True Tone: On",
    "Two side-by-side resizable panes separated by a divider.": "Two side-by-side resizable panes separated by a divider.",
    "Two stacked resizable panes separated by a divider.": "Two stacked resizable panes separated by a divider.",
    "Ultra Thick": "Ultra Thick",
    "Ultra Thin": "Ultra Thin",
    "Unredacted text": "Unredacted text",
    "VSplitView": "VSplitView",
    "Value gauge with labels": "Value gauge with labels",
    "Vertical Spacing": "Vertical Spacing",
    "Visual stand-in for the black “Sign in with Apple” button; auth is a no-op.": "Visual stand-in for the black “Sign in with Apple” button; auth is a no-op.",
    "Volume": "Volume",
    "Whole new body!": "Whole new body!",
    "Wi-Fi: Connected": "Wi-Fi: Connected",
    "With": "With",
    "Word count: 0": "Word count: 0",
    "Your password is ": "Your password is ",
    "a": "a",
    "bordered": "bordered",
    "borderless": "borderless",
    "heart.fill": "heart.fill",
    "highPriorityGesture": "highPriorityGesture",
    "link": "link",
    "max": "max",
    "menu.localization.title": "Language",
    "min": "min",
    "plain": "plain",
    "simultaneousGesture": "simultaneousGesture",
    "unavailable": "unavailable",
    "withAnimation": "withAnimation",
    "🔖": "🔖",
  ]

  static let uk: [String: String] = [
    "(disabled under strict concurrency — see TaskDemo.swift)": "(вимкнено за суворого режиму паралельності — див. TaskDemo.swift)",
    ".animation": ".animation",
    ".modifier": ".modifier",
    ".move(edge: .leading)": ".move(edge: .leading)",
    ".offset(x: 100, y: 100)": ".offset(x: 100, y: 100)",
    ".opacity": ".opacity",
    ".opacity + .slide": ".opacity + .slide",
    ".opacity/.scale": ".opacity/.scale",
    ".resizable() filling a 96×48 frame": ".resizable() що заповнює кадр 96×48",
    ".scale": ".scale",
    ".scaledToFill() (object-fit)": ".scaledToFill() (object-fit)",
    ".scaledToFit() (object-fit: contain)": ".scaledToFit() (object-fit: contain)",
    ".slide": ".slide",
    "0": "0",
    "1": "1",
    "1-10": "1-10",
    "1. Set the color to yellow": "1. Встановити колір жовтим",
    "11-20": "11-20",
    "1st tap gesture": "1-й жест торкання",
    "2. Transform if the color is yellow -> green": "2. Перетворити, якщо колір жовтий -> зелений",
    "3. Transform if the color is green -> blue": "3. Перетворити, якщо колір зелений -> синій",
    "4. Use the final color in an overlay.": "4. Використати фінальний колір у накладенні.",
    "<font color='red'>Sanitized Text in Unsanitized VStack</font>": "<font color='red'>Sanitized Text in Unsanitized VStack</font>",
    "<font color='red'>Sanitized Text</font>": "<font color='red'>Sanitized Text</font>",
    "<font color='red'>Segmented ": "<font color='red'>Segmented ",
    "<font color='red'>Text in Unsanitized VStack</font>": "<font color='red'>Text in Unsanitized VStack</font>",
    "<font color='red'>Unsanitized Text</font>": "<font color='red'>Unsanitized Text</font>",
    "Account": "Обліковий запис",
    "Actions": "Дії",
    "Adaptive LazyVGrid": "Адаптивна LazyVGrid",
    "Add item": "Додати елемент",
    "An unlabeled group box groups related controls together.": "Блок групи без підпису об'єднує пов'язані елементи керування.",
    "Appointment date:": "Дата зустрічі:",
    "Appointment time:": "Час зустрічі:",
    "Async `.task` fetch demo": "Демо асинхронного завантаження `.task`",
    "Blue Style": "Синій стиль",
    "Bookmark": "Закладка",
    "Bottom": "Знизу",
    "Bottom Pane": "Нижня панель",
    "Brightness: 80%": "Яскравість: 80%",
    "Button": "Кнопка",
    "Circular gauge style": "Круглий стиль індикатора",
    "Commits: 0": "Коміти: 0",
    "Committed: —": "Зафіксовано: —",
    "Complex": "Складний",
    "Confirm:": "Підтвердити:",
    "Console content": "Вміст консолі",
    "Content of Tab One": "Вміст першої вкладки",
    "Content of Tab Two": "Вміст другої вкладки",
    "Custom Font": "Власний шрифт",
    "Decorative (empty alt)": "Декоративний (порожній alt)",
    "Default": "Типово",
    "Default color: red (this won't show on the innermost because it never 'changed').": "Типовий колір: червоний (не відображатиметься у найглибшому елементі, бо він ніколи не «змінювався»).",
    "Default label (title + icon)": "Типовий підпис (заголовок + іконка)",
    "Delay": "Затримка",
    "Delete / reorder affordances appear while editMode.isEditing.": "Елементи видалення та впорядкування відображаються, поки editMode.isEditing активний.",
    "Detail content": "Вміст деталей",
    "Determinate": "Визначений",
    "Display": "Дисплей",
    "Drag Gestures": "Жести перетягування",
    "DynamicViewContent": "DynamicViewContent",
    "EditButton": "EditButton",
    "Editor content": "Вміст редактора",
    "End of section": "Кінець розділу",
    "Ethernet: Off": "Ethernet: Вимк.",
    "Fallback Font": "Резервний шрифт",
    "Favorite": "Улюблене",
    "Fill, with a custom label": "Заповнення з нестандартним підписом",
    "First slider has steps at 0.3, 0.6, 0.9; second one has stops every 1/3 of the way": "Перший повзунок має позначки на 0.3, 0.6, 0.9; другий — через кожну 1/3 шляху",
    "Forced to bottom.": "Примусово внизу.",
    "Green Style": "Зелений стиль",
    "Grouped Transition": "Згрупований перехід",
    "HSplitView": "HSplitView",
    "Hello, world!": "Привіт, світе!",
    "Horizontal Spacing": "Горизонтальний відступ",
    "I'm all fancy": "Я такий вишуканий",
    "I'm forced to the top": "Мене примусово розміщено вгорі",
    "I'm on bottom": "Я внизу",
    "I'm on top": "Я вгорі",
    "Icon-only style": "Лише іконка",
    "Increased Total": "Збільшений підсумок",
    "Indeterminate": "Невизначений",
    "Innermost child sets the color to blue.": "Найвкладеніший елемент встановлює колір синім.",
    "I’m always checked!": "Я завжди позначений!",
    "Label": "Мітка",
    "Language": "Мова",
    "Last action: None": "Остання дія: Немає",
    "LazyHStack": "LazyHStack",
    "LazyVStack": "LazyVStack",
    "Left": "Ліворуч",
    "Left Pane": "Ліва панель",
    "Left side.": "Ліва сторона.",
    "Lightning": "Блискавка",
    "Limit exceeded": "Ліміт перевищено",
    "Linear gauge style": "Стиль лінійного індикатора",
    "Load": "Завантажити",
    "Localization": "Локалізація",
    "LongPress Gestures": "Жести довгого натискання",
    "Named (data-URI) source": "Іменоване джерело (data-URI)",
    "Not tapped": "Не натиснуто",
    "One level up sets the color to green, and so on.": "Рівень вище встановлює зелений колір, і так далі.",
    "Paste": "Вставити",
    "PasteButton": "PasteButton",
    "Pasted: None": "Вставлено: Нічого",
    "Pick a text style...": "Виберіть стиль тексту...",
    "Preferences are like reverse-environment values.": "Параметри — це значення середовища у зворотному напрямку.",
    "Preferences can also be accessed and used immediately via a background or overlay:": "Параметри також можна отримати та використати одразу через фон або накладання:",
    "Pressed": "Натиснуто",
    "Primary": "Основний",
    "Progress": "Прогрес",
    "Quaternary": "Четвертинний",
    "Reads plain-text strings from the clipboard via payloadAction.": "Зчитує рядки у форматі звичайного тексту з буфера обміну через payloadAction.",
    "Red Style": "Червоний стиль",
    "Regular": "Звичайний",
    "Repeated Animation": "Повторювана анімація",
    "Right": "Праворуч",
    "Right Pane": "Права панель",
    "Right side.": "Права сторона.",
    "Root": "Корінь",
    "Secondary": "Другорядний",
    "Selection: 0": "Вибір: 0",
    "Sidebar content": "Вміст бічної панелі",
    "Sign in with Apple": "Увійти через Apple",
    "SignInWithAppleButton": "SignInWithAppleButton",
    "Simple LazyHGrid": "Simple LazyHGrid",
    "Simple value gauge": "Простий індикатор значення",
    "Some nav-text": "Some nav-text",
    "Speed": "Швидкість",
    "Star": "Зірка",
    "Status: Live": "Статус: активний",
    "Style": "Стиль",
    "Styles": "Стилі",
    "Switch the app language. On the web the page reloads with the new language.": "Змінити мову застосунку. В браузері сторінка перезавантажиться з новою мовою.",
    "System symbol (web placeholder — no SF Symbol pipeline)": "Системний символ (веб-замінник — без конвеєра SF Symbol)",
    "THICK TEXT": "ЖИРНИЙ ТЕКСТ",
    "Tab One": "Вкладка 1",
    "Tab Two": "Вкладка 2",
    "Tap Gestures": "Жести дотику",
    "Tap to toggle edit mode.": "Торкніться, щоб увімкнути режим редагування.",
    "Tertiary": "Третинний",
    "Text style": "Стиль тексту",
    "Text: “”": "Текст: “”",
    "Text</font>": "Text</font>",
    "Thick": "Товстий",
    "Thin": "Тонкий",
    "This is super important": "Це дуже важливо",
    "This is the inital text": "Це початковий текст",
    "This text has been concatenated": "Цей текст було об'єднано",
    "This was super important": "Це було дуже важливо",
    "Title and icon style": "Стиль із заголовком та іконкою",
    "Title-only style": "Стиль лише із заголовком",
    "Tokamak Demo": "Tokamak Demo",
    "Top": "Зверху",
    "Top Pane": "Верхня панель",
    "True Tone: On": "True Tone: Увімкнено",
    "Two side-by-side resizable panes separated by a divider.": "Дві панелі зі змінним розміром, розташовані поруч і розділені роздільником.",
    "Two stacked resizable panes separated by a divider.": "Дві панелі зі змінним розміром, розташовані одна над одною і розділені роздільником.",
    "Ultra Thick": "Надтовстий",
    "Ultra Thin": "Надтонкий",
    "Unredacted text": "Нередагований текст",
    "VSplitView": "VSplitView",
    "Value gauge with labels": "Індикатор значення з мітками",
    "Vertical Spacing": "Вертикальний відступ",
    "Visual stand-in for the black “Sign in with Apple” button; auth is a no-op.": "Візуальна замінна для чорної кнопки “Вхід через Apple”; авторизація не виконується.",
    "Volume": "Гучність",
    "Whole new body!": "Абсолютно нове тіло!",
    "Wi-Fi: Connected": "Wi-Fi: Підключено",
    "With": "З",
    "Word count: 0": "Кількість слів: 0",
    "Your password is ": "Ваш пароль: ",
    "a": "a",
    "bordered": "bordered",
    "borderless": "borderless",
    "heart.fill": "heart.fill",
    "highPriorityGesture": "highPriorityGesture",
    "link": "link",
    "max": "max",
    "menu.localization.title": "Мова",
    "min": "min",
    "plain": "plain",
    "simultaneousGesture": "simultaneousGesture",
    "unavailable": "unavailable",
    "withAnimation": "withAnimation",
    "🔖": "🔖",
  ]
}
