#!/usr/bin/env bash
# Copyright 2020 Tokamak contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# gtk screenshot driver (best-effort, AC-6/AC-8).
#
# Builds the dedicated Linux + GTK4 + Xvfb image from `Dockerfile.gtk` (NOT the wasm
# `Dockerfile`), then under one Xvfb runs `TokamakGTKDemo` once per catalog id and
# captures each mapped window with ImageMagick `import` into
# screenshots/gtk/<sanitize(name)>.png. Unsupported demos (deny-set or runtime) are
# logged to screenshots/gtk/UNSUPPORTED.md with real per-entry reasons.
#
# EVERY path exits 0 — gtk never blocks the must-pass mac/web/ios subset:
#   * Docker daemon unavailable -> write SKIPPED.md, exit 0.
#   * Image build fails (renderer did not compile) -> write UNSUPPORTED.md (build:) +
#     build-error.log, keep SKIPPED.md, exit 0 (AC-8 degradation).
#   * >=1 PNG captured -> remove stale SKIPPED.md, exit 0.

set -uo pipefail
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/screenshots/gtk"
mkdir -p "$OUT"

write_skipped() {
  cat > "$OUT/SKIPPED.md" <<EOF
# gtk screenshots — SKIPPED

$1

## How to produce gtk screenshots

\`\`\`sh
# from the repo root, with a running Docker daemon:
bash Scripts/screenshots/gtk-docker.sh
# -> builds Dockerfile.gtk (Linux+GTK4+Xvfb), runs TokamakGTKDemo per catalog id,
#    captures each window into screenshots/gtk/<name>.png
\`\`\`
EOF
}

# --- Docker daemon pre-flight ------------------------------------------------
if ! docker info >/dev/null 2>&1; then
  write_skipped "Docker daemon not reachable (\`docker info\` failed) at $(date -u +%Y-%m-%dT%H:%M:%SZ)."
  echo "[skip] gtk: Docker daemon unavailable -> wrote SKIPPED.md"
  exit 0
fi

# --- Build the dedicated GTK image -------------------------------------------
BUILD_LOG="$OUT/build-error.log"
echo "[gtk] building Dockerfile.gtk (this is slow on a cold cache)…"
if ! docker build -f "$ROOT/Dockerfile.gtk" -t tokamak-gtk "$ROOT" >"$BUILD_LOG" 2>&1; then
  echo "[gtk] image build FAILED — renderer did not compile (AC-8 degradation)"
  {
    echo "# gtk — unsupported demos"
    echo ""
    echo "- (all demos) — build: TokamakGTKDemo did not compile inside Dockerfile.gtk"
    echo ""
    echo "## Build error (last 120 lines)"
    echo ""
    echo '```'
    tail -n 120 "$BUILD_LOG"
    echo '```'
  } > "$OUT/UNSUPPORTED.md"
  write_skipped "The GTK4 image build failed (renderer did not compile). See screenshots/gtk/build-error.log and UNSUPPORTED.md."
  echo "[gtk] wrote UNSUPPORTED.md (build:) + kept SKIPPED.md"
  exit 0
fi
# Build succeeded: the error log is not needed.
rm -f "$BUILD_LOG"
echo "[gtk] image built: tokamak-gtk"

# --- Capture: one window per catalog id, under one Xvfb ----------------------
# The capture loop runs INSIDE the container (bash -c). It enumerates ids via
# `--list`, then renders + captures each non-denied entry, writing PNGs and
# UNSUPPORTED.md into the bind-mounted /out.
docker run --rm \
  -v "$OUT:/out" \
  -e TOKAMAK_GTK_LIST= \
  tokamak-gtk \
  bash -c '
    set -u
    BIN=.build/debug/TokamakGTKDemo
    Xvfb :99 -screen 0 1280x900x24 >/dev/null 2>&1 &
    XVFB_PID=$!
    sleep 2
    export DISPLAY=:99

    # Fresh UNSUPPORTED.md each run; remove stale SKIPPED.md only after >=1 capture.
    : > /out/UNSUPPORTED.md
    echo "# gtk — unsupported demos" >> /out/UNSUPPORTED.md
    echo "" >> /out/UNSUPPORTED.md
    echo "Regenerated by Scripts/screenshots/gtk-docker.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)." >> /out/UNSUPPORTED.md
    echo "Each line is a real per-entry outcome from this capture run." >> /out/UNSUPPORTED.md
    echo "" >> /out/UNSUPPORTED.md
    echo "> NOTE: TokamakGTK4 now attaches the view tree (GTK3->GTK4 attach fix:" >> /out/UNSUPPORTED.md
    echo "> gtk_window_set_child for the window child, real GtkBox for stacks), so many" >> /out/UNSUPPORTED.md
    echo "> demos render REAL distinct content -> screenshots/gtk/<Name>.png. The entries" >> /out/UNSUPPORTED.md
    echo "> below are the demos that still do NOT render distinctly: deny-set primitives the" >> /out/UNSUPPORTED.md
    echo "> backend never implemented, and views that map a window but paint no content (the" >> /out/UNSUPPORTED.md
    echo "> capture is the ~3-colour blank window chrome; rejected by the colour-count gate)." >> /out/UNSUPPORTED.md
    echo "> Those need further per-primitive renderer work, which is beyond this change." >> /out/UNSUPPORTED.md
    echo "" >> /out/UNSUPPORTED.md

    sanitize() { printf "%s" "$1" | sed "s#.*/##; s#/#-#g; s/ /-/g"; }

    CAPTURED=0
    IDS=$("$BIN" --list 2>/dev/null | sed -n "s/^ID //p")
    while IFS= read -r id; do
      [ -n "$id" ] || continue
      name="${id##*/}"
      png="/out/$(sanitize "$id").png"

      # Run one entry in the background; capture its stderr to detect deny/runtime.
      tmperr=$(mktemp)
      TOKAMAK_GTK_DEMO="$id" "$BIN" >/dev/null 2>"$tmperr" &
      pid=$!

      # If the entry was deny-listed it exits 0 almost immediately, printing
      # "UNSUPPORTED <id>: deny-set: …". Give it a beat, then check.
      sleep 0.4
      if grep -q "deny-set:" "$tmperr" 2>/dev/null; then
        reason=$(sed -n "s/^UNSUPPORTED [^:]*: //p" "$tmperr" | head -1)
        echo "- $id — ${reason:-deny-set: primitive not implemented in TokamakGTK4}" >> /out/UNSUPPORTED.md
        kill "$pid" 2>/dev/null; wait "$pid" 2>/dev/null
        rm -f "$tmperr"
        continue
      fi

      # Poll up to ~8s for a mapped, visible top-level window; capture its id.
      found=0; tries=0; winid=""
      while [ "$tries" -lt 16 ]; do
        if ! kill -0 "$pid" 2>/dev/null; then
          # Process exited before mapping a window -> runtime failure.
          break
        fi
        winid=$(xdotool search --onlyvisible --name "" 2>/dev/null | tail -1)
        if [ -n "$winid" ]; then
          found=1; break
        fi
        sleep 0.5; tries=$((tries+1))
      done

      if [ "$found" -eq 1 ]; then
        sleep 1.2   # settle: let GTK lay out + paint the widget tree
        # Capture the SPECIFIC demo window (cleaner than the whole root); fall back to
        # the root if the window id grab fails for any reason.
        if [ -n "$winid" ]; then
          import -window "$winid" "$png" 2>/dev/null || import -window root "$png" 2>/dev/null || true
        else
          import -window root "$png" 2>/dev/null || true
        fi
        # FRAMING FIX: `import -window root` grabs the whole 1280x900 Xvfb screen, so the
        # ~200px of real content sits top-left on a big black field. Crop the uniform black
        # surround to the content bounding box, then add light breathing room. The leading
        # 1px black border makes `-trim` reliable; `-fuzz` absorbs anti-aliasing; `+repage`
        # resets the canvas offset; the final light border matches the content background.
        # Only keep the trim if it stays a valid, non-degenerate PNG — else keep the
        # untrimmed capture (the colour/blank gate below still applies to whatever remains).
        if [ -s "$png" ]; then
          trimmed="${png}.trim.png"
          if convert "$png" -bordercolor black -border 1 -fuzz 12% -trim +repage \
               -bordercolor "#f5f5f5" -border 16 "$trimmed" 2>/dev/null \
             && [ -s "$trimmed" ] \
             && [ "$(od -An -tx1 -N4 "$trimmed" 2>/dev/null | tr -d " \n")" = "89504e47" ] \
             && [ "$(identify -format "%k" "$trimmed" 2>/dev/null | tr -dc 0-9)" -gt 1 ] 2>/dev/null; then
            mv -f "$trimmed" "$png"
          else
            rm -f "$trimmed"
            echo "[gtk] trim skipped for $name (kept untrimmed capture)" >&2
          fi
        fi
        # Verify via the PNG magic bytes (\x89PNG) — `file` is NOT installed in the
        # jammy image, so a `file | grep "PNG image"` check silently rejects every
        # valid capture. `od` is part of coreutils and always present.
        if [ -s "$png" ] && [ "$(od -An -tx1 -N4 "$png" 2>/dev/null | tr -d " \n")" = "89504e47" ]; then
          # BLANK-WINDOW REJECTION: an incomplete primitive maps a window but paints no
          # content -> the capture is just GTK window chrome (a ~3-colour 2-bit blank).
          # Real renders have dozens-to-hundreds of colours. `identify -format %k` gives
          # the unique-colour count; <=4 means the demo did not paint distinct content,
          # so it is NOT a real capture -> demote to UNSUPPORTED instead of shipping a
          # blank under a per-demo name (which would misrepresent coverage + create
          # byte-identical duplicates).
          colors=$(identify -format "%k" "$png" 2>/dev/null | tr -dc "0-9")
          colors=${colors:-0}
          if [ "$colors" -le 4 ]; then
            rm -f "$png"
            echo "- $id — runtime: window mapped but primitive painted no distinct content ($colors colours; renderer incomplete for this view)" >> /out/UNSUPPORTED.md
          else
            CAPTURED=$((CAPTURED+1))
            echo "[gtk] captured $name -> $(basename "$png") ($colors colours)" >&2
          fi
        else
          rm -f "$png"
          echo "- $id — runtime: capture produced no valid PNG" >> /out/UNSUPPORTED.md
        fi
      else
        # No window mapped: distinguish a clean runtime reject (stderr) from a trap.
        if grep -q "runtime:" "$tmperr" 2>/dev/null; then
          reason=$(sed -n "s/^UNSUPPORTED [^:]*: //p" "$tmperr" | head -1)
          echo "- $id — ${reason:-runtime: aborted before window map}" >> /out/UNSUPPORTED.md
        else
          echo "- $id — runtime: aborted before window map (renderer incomplete)" >> /out/UNSUPPORTED.md
        fi
      fi

      kill "$pid" 2>/dev/null; wait "$pid" 2>/dev/null
      rm -f "$tmperr"
    done <<EOF
$IDS
EOF

    kill "$XVFB_PID" 2>/dev/null

    # --- Degenerate-gallery gate ------------------------------------------------
    # TokamakGTK4 is incomplete: it maps a window but often does not attach the
    # SwiftUI view tree (gtk_box_append/GTK_IS_BOX warnings), so every per-demo
    # capture is the SAME blank window chrome. `import -window root` then yields N
    # byte-identical PNGs. Committing those under per-demo names (Counter.png,
    # Text.png, …) misrepresents coverage and violates the repo dup invariant
    # (assertNoDuplicateRenders). If the captures collapse to a SINGLE distinct
    # md5, keep exactly ONE as `window.png` (a build/pipeline PROOF, not a demo)
    # and drop the per-demo copies, logging that no distinct content was produced.
    DISTINCT=$(md5sum /out/*.png 2>/dev/null | cut -d" " -f1 | sort -u | wc -l | tr -d " ")
    PNGN=$(ls /out/*.png 2>/dev/null | wc -l | tr -d " ")
    if [ "$PNGN" -gt 1 ] && [ "$DISTINCT" -le 1 ]; then
      echo "[gtk] all $PNGN captures are byte-identical (renderer painted no distinct content)" >&2
      keep=$(ls /out/*.png 2>/dev/null | head -1)
      cp "$keep" /out/window.png 2>/dev/null
      for f in /out/*.png; do
        [ "$f" = "/out/window.png" ] && continue
        rm -f "$f"
      done
      echo "" >> /out/UNSUPPORTED.md
      echo "> DEGENERATE GALLERY: all $PNGN per-demo captures were byte-identical blank" >> /out/UNSUPPORTED.md
      echo "> windows; collapsed to a single screenshots/gtk/window.png build/pipeline proof." >> /out/UNSUPPORTED.md
      echo "> NO demo rendered distinct content (renderer incomplete — out of scope)." >> /out/UNSUPPORTED.md
      CAPTURED=0   # 0 DISTINCT demos; window.png is a proof artifact, not a demo capture.
    fi

    echo "[gtk] distinct-demo captures: $CAPTURED (window.png is a build proof when 0)" >&2
    # Signal distinct-demo count to the host via a marker file.
    echo "$CAPTURED" > /out/.captured_count
  ' || echo "[gtk] docker run returned non-zero (tolerated; see screenshots/gtk/)"

# --- Post-run accounting -----------------------------------------------------
# DISTINCT = number of distinct-content demos (0 when the gallery degenerated to the
# single window.png proof). N = raw PNG files on disk (>=1 when window.png exists).
DISTINCT=$(cat "$OUT/.captured_count" 2>/dev/null || echo 0)
N=$(ls "$OUT"/*.png 2>/dev/null | wc -l | tr -d ' ')
rm -f "$OUT/.captured_count"
if [ "$N" -gt 0 ]; then
  # An artifact exists (>=1 real PNG: distinct demos OR the window.png build proof),
  # so a real attempt was made -> drop the stale SKIPPED.md.
  rm -f "$OUT/SKIPPED.md"
  if [ "$DISTINCT" -gt 0 ]; then
    echo "[gtk] $DISTINCT distinct-demo PNG(s) -> removed stale SKIPPED.md"
  else
    echo "[gtk] 0 distinct demos; kept window.png build/pipeline proof -> removed stale SKIPPED.md"
  fi
else
  write_skipped "The GTK4 image built and ran, but no window/PNG was produced (renderer incomplete by design — see UNSUPPORTED.md)."
  echo "[gtk] no PNG produced -> wrote SKIPPED.md"
fi

echo "[summary] gtk: $DISTINCT distinct demo(s), $N PNG file(s) on disk; see screenshots/gtk/UNSUPPORTED.md"
exit 0
